Added image endpoints
infalliblePirate/got-explorer pull request #11
Opened 2024-12-08 17:58 UTC by andriiavdiiuk

Merge after merging PR #7.

2024-12-11 11:16 UTC, Evgeniy1996 requested changes
The images must be validated. We should check that the submitted file is image and check the size limits
The returned result should e validation result same as in auth pr

2024-12-11 11:16 UTC, Evgeniy1996 commented on GotExplorer.API/Controllers/ImageController.cs
> +        public async Task<IActionResult> GetImageById(int id)
I would recommend to use GUID as ID

2024-12-11 11:16 UTC, Evgeniy1996 commented on GotExplorer.API/Controllers/ImageController.cs
> +        public async Task<IActionResult> GetAllImages()
Do we need this endpoint for frontend

2024-12-11 11:16 UTC, Evgeniy1996 commented on GotExplorer.API/Extensions/ServiceResultToActionResultExtensions.cs
Same as in auth PR

2025-02-04 19:57 UTC, infalliblePirate approved these changes

2025-02-05 20:41 UTC, uliaescha approved these changes

2025-02-05 20:41 UTC, uliaescha approved these changes

2025-02-05 22:24 UTC, lizabre approved these changes

2025-02-06 22:10 UTC, merged