Added authorization endpoints and some fixes
infalliblePirate/got-explorer pull request #6
Opened 2024-11-15 14:55 UTC by andriiavdiiuk

Added authorization endpoints and some small fixes.
Added global error handling, automapper, and CORS to allow requests only from our client origin.

Merge after merging PR #4.

2024-11-25 13:10 UTC, Evgeniy1996 commented on GotExplorer.API/Configuration/CorsSettings.cs
> +            return builder.Build();
I suggest that this class should not exist. I would recommend to avoid use AllowAnyOrigin, AllowAnyMethod, AllowAnyHeader at total

2024-11-25 13:12 UTC, Evgeniy1996 commented on GotExplorer.API/Middleware/GlobalExceptionHandler.cs
> +            };
Why do we need this switch at all, we need just map the status codes to response.

2024-12-11 11:09 UTC, Evgeniy1996 requested changes
Change the logic to avoid use the problemdetail and use validation result as a returned type

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.API/Program.cs
>  namespace GotExplorer.API
empty line

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.API/Extensions/ServiceResultToActionResultExtensions.cs
> +            };
Status code 422  when more than one error was happen. 
My suggestion is to return body as a response in case "prop" : "validation message"

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.API/Extensions/ServiceResultToActionResultExtensions.cs
> +    public static class ServiceResultToActionResultExtensions
Do not use Problemdetails at all. Please provide details as a validation result from fluent api

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.BLL/Services/UserService.cs
> +                        new ValidationFailure(nameof(loginDTO.Password), "Username not found and/or password incorrect"),
Duplicate of error

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.BLL/Services/UserService.cs
> +                        new ValidationFailure(nameof(loginDTO.Password), "Username not found and/or password incorrect"),
same

2024-12-11 11:09 UTC, Evgeniy1996 commented on GotExplorer.BLL/Services/UserService.cs
> +                return serviceResult;
Validation result should be returned

2024-12-23 09:24 UTC, Evgeniy1996 requested changes

2024-12-23 09:24 UTC, Evgeniy1996 commented on GotExplorer.BLL/Services/Results/ServiceResult.cs
> +        public ValidationResult? ValidationResult { get; set; } = null;
You do not need this wrapper. You need just to use ValidationResult and other native classes from fluent validation library

2025-02-04 19:51 UTC, infalliblePirate approved these changes

2025-02-05 22:22 UTC, lizabre approved these changes

2025-02-06 22:05 UTC, merged